### ISSUE TITLE
On demand - event date always 7 days old

### ISSUE THREAD

**Issue by camhef** [sterd71/plugin.video.eurosporton#14]
**On TV** items show with the current date, as I would expect.  All **On demand** items show as **current date minus 7 days**.

For example, On TV now:  Eurosport 2: European Championship | Woman's 49kg.  First aired: 03/04/2021
Exactly the same item in On demand (latest item) in Weightlifting. First aired: 27/03/2021

This has been an issue for a while; present in version 0.2.1 and the previous version I had installed.

Tested after reboot and system clock/time is correct.

**Comment by sterd71** [comment]
I'm not sure what issue you are raising here.

The addon has no control over what items Eurosport are broadcasting or making available to be viewed OnDemand.

All of the information displayed on screen is provided by Eurosport, so the dates and event titles are displayed as provided.

Are you sure exactly the same video was being shown on tv that was available on demand?
Was the item being shown on tv a repeat of an item that had been broadcast before?
Very often they will broadcast a number of items from the same tournament but give them the same name.  Could this have been different rounds of the same competition?
