### ISSUE TITLE
Inputstream Adaptive (un)requirement

### ISSUE THREAD

**Issue by drnovsek** [sterd71/plugin.video.eurosporton#3]
No streams will play unless plugin "Inputstream Adaptive" is disabled (or deleted).

I have tried this on 2 different devices (LibreElec and Kodi for macOS) and seen the same behaviour.

I can see IA plugin being listed as a requirement though.

I have noticed in the logs that when not working the error reported is: 
`WARNING: OpenStream - Unsupported stream 1001. Stream disabled.`

See rest of the log for more details.

I have no idea how to troubleshoot this other than disabling, which in turn brakes Netflix plugin.

Any ideas welcome.
[ESP-log.txt](https://github.com/sterd71/plugin.video.eurosporton/files/5034745/ESP-log.txt)

**Comment by sterd71** [comment]
There have been a number of updates to the InputStream Adaptive plugin since this issue was raised.

Currently all streams are working as expected so closing issue.
