### ISSUE TITLE
Kodi becomes unresponsive when opening info screen

### ISSUE THREAD

**Issue by peskdale** [sterd71/plugin.video.eurosporton#5]
While watching a live stream, opening up the info screen - either by pressing 'i' on the keyboard/remote or by selecting from the player bar - causes Kodi to stop responding to further commands.

I have to restart Kodi in order to fix this issue.

This is happening to me in adaptive ISM and ffmpeg HLS. Can't test adaptive HLS as my inputstream.adaptive version isn't new enough.

**Comment by sterd71** [comment]
Hi,

Apologies for taking such a long time to respond.  I've tried this and it works fine for me.  

Bringing up the information panel doesn't cause Kodi to stop responding.

Is this still an issue for you?

**Comment by peskdale** [comment]
I'm afraid I've not used this app since September - I was only using it for one event. So I can't say if this is still the case.
