### ISSUE TITLE
Not all streams are available

### ISSUE THREAD

**Issue by pandvan** [sterd71/plugin.video.eurosporton#6]
I've noticed that not all live streams are always available on "On now" folder.
For example today, during the 24h or Le Mans, using ES official app there were several streams aside from the main ones of E1 and E2 with an alternative commentator and car onboards. They weren't reachable using the add-on.
Once then event completed, they are available on "On earlier" folder.

**Comment by pandvan** [comment]
It might have been only a temporary issue with ES Player API.
After opening this issue, there were missing streams also on ES Player web site (not in the app).
In the evening I've checked again with the add-on and all additional streams were available.
I'm sorry for this (more likely) noise.

**Comment by andy29429** [comment]
This evening I was looking for the Le Mans coverage being shown on Eurosport 1, but only Eurosport 2 and the Manchester Open extra stream were listed in the 'on now' section. Then a bit later it was only the Open in the list. Now, a couple of hours later, there is nothing.

**Comment by sterd71** [comment]
The On Now section of the addon has been removed due to a change in the Eurosport API.
