### ISSUE TITLE
Only on demand works

### ISSUE THREAD

**Issue by ozzymanborn** [sterd71/plugin.video.eurosporton#7]
I don't know it's api issue but this morning only on demand section working... Other three sections showing empty...

**Comment by peskdale** [comment]
The API has changed.

The request now needs to include the following headers:
```
x-disco-client: WEB:UNKNOWN:esplayer:prod
x-disco-params: realm=eurosport,,
```

**Comment by pandvan** [comment]
Thank you so much @peskdale for your pull request.
Just tried with manually patching my add-on installation an it works back again. Just in time to watch the 24h of Le Mans...

**Comment by andy29429** [comment]
Yes! Thank you @peskdale !

**Comment by ozzymanborn** [comment]
@peskdale Patch fixed the issue but when events went next day it's dissapeared from schedule again... I mean le mans event appeared on schedule during day still 19.09 but 20.09 All Le Mans Feeds lost. (Might be need a schedule page)

**Comment by peskdale** [comment]
@ozzymanborn Not sure what you experienced, but seems to be working for me this morning.

Suspect this is some wierdness on Eurosport’s end with Le Mans being an overnight programme. Looks like they scheduled a 'Part 2' from 01:00 GMT. So for that hour or two between wherever your midnight is and then, Le Mans would not have shown up on the plugin, as it wasn't on "todays" schedule. This is an API limitation.

**Comment by ozzymanborn** [comment]
> @ozzymanborn Not sure what you experienced, but seems to be working for me this morning.
> 
> Suspect this is some wierdness on Eurosport’s end with Le Mans being an overnight programme. Looks like they scheduled a 'Part 2' from 01:00 GMT. So for that hour or two between wherever your midnight is and then, Le Mans would not have shown up on the plugin, as it wasn't on "todays" schedule. This is an API limitation.

Yes it was that... Previous plugin had schedule section for these kind of glitches I don't know is it possible for current api/plugin....

**Comment by pandvan** [comment]
I can confirm that at 00:20 GMT, when I stop watching, no more Le Mans streams are available on "On Now" list.
When I started watching again, at about 03:00 GMT, they were present.

**Comment by peskdale** [comment]
Yes, as I say... API limitation combined with bad scheduling.

It’s may have been that the live streams would have still been watchable via the on demand section (the HLS streams would still have been in live mode on Eurosport’s server until 2am), but obviously can’t test that after the event. Only a theory unfortunately.

Either way, schedules are working with the attached PR, so the original issue of no schedules is resolved... pending a merge by the maintainer.

**Comment by sterd71** [comment]
Headers have been updated in code on 25/9/20 to correct issue.
